/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPurchasesPanel.java
 *
 * Created on 17/07/2010, 04:39:50 PM
 */
package gui.purchases;

import bussiness.Article;
import bussiness.Customer;
import bussiness.Purchase;
import common.Constants;
import common.InputValidator;
import common.MainPanelInterface;
import common.ValidationException;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PurchasesModel;

/**
 *
 * @author Luc3
 */
public class MainPurchasesPanel extends javax.swing.JPanel implements MainPanelInterface {

    PurchasesModel model = new PurchasesModel();

    /** Creates new form MainPurchasesPanel */
    public MainPurchasesPanel() {
        initComponents();
        deletePurchase.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        articleSearchPanel1 = new gui.article.ArticleSearchPanel();
        addPurchase = new javax.swing.JButton();
        amountArtText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchasesPanel = new common.CustomTable();
        deletePurchase = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(663, 452));

        addPurchase.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        addPurchase.setText("AGREGAR");
        addPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPurchaseActionPerformed(evt);
            }
        });

        amountArtText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountArtTextMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad: ");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel2.setText("Precio Compra:");

        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });

        purchasesPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        purchasesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasesPanelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchasesPanel);

        deletePurchase.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        deletePurchase.setText("ELIMINAR COMPRA");
        deletePurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePurchaseMouseClicked(evt);
            }
        });
        deletePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePurchaseActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jButton2.setText("REGISTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(priceText)
                                    .addComponent(amountArtText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addComponent(addPurchase))
                            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(deletePurchase)))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(articleSearchPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(articleSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(amountArtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPurchase))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletePurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void validateInput() throws ValidationException {


        boolean isValidamount = InputValidator.validateText2(amountArtText);
        boolean isValidlprice = InputValidator.validateText2(priceText);

        if (isValidamount || isValidlprice) {

            throw new ValidationException(InputValidator.GENERAL_ERROR);
        }


    }

    private void addPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPurchaseActionPerformed
        try {
            validateInput();
        } catch (ValidationException ex) {
            
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage());
            amountArtText.setForeground(Color.black);
        }

        int amount = Integer.parseInt(amountArtText.getText());
        double price = Double.parseDouble(priceText.getText());
        Purchase purchase = new Purchase(model.getSelectedArticle().getDescripcion(), model.getSelectedArticle().getid_A(), amount, price, Constants.getCurrentDate());
        model.addPurchase(purchase);

        updateTableModel();


    }//GEN-LAST:event_addPurchaseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            if (model.getPurchasesSize() == 0) {
                JOptionPane.showMessageDialog(this, "No tiene ninguna Compra registrada");
            } else {
                model.insertPuchases();
                JOptionPane.showMessageDialog(this, "La compra ha sido registrada exitosamente");
            }//else
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deletePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePurchaseActionPerformed

        if (model.getSelectedIndex() == null) {
            JOptionPane.showMessageDialog(this, "No tiene compra seleccionada");
        } else if (Constants.confirmDialog(this, "Está seguro de que desea eliminar la compra seleccionada? ")) {


            model.removePurchase(); 
            updateTableModel();
            model.setSelectedIndex(null);
        }


    }//GEN-LAST:event_deletePurchaseActionPerformed

    private void deletePurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePurchaseMouseClicked
    }//GEN-LAST:event_deletePurchaseMouseClicked

    private void purchasesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasesPanelMouseClicked

        model.setSelectedIndex(new Integer(purchasesPanel.getSelectedIndex()));
        deletePurchase.setEnabled(true);

    }//GEN-LAST:event_purchasesPanelMouseClicked

    private void amountArtTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountArtTextMouseClicked
    }//GEN-LAST:event_amountArtTextMouseClicked

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    private void updateTableModel() {

        DefaultTableModel tableModel = new DefaultTableModel();
        int total = Integer.parseInt(amountArtText.getText());
        tableModel.addColumn("Cantidad");
        tableModel.addColumn("Descripción");
        tableModel.addColumn("Total de Compra");


        for (int i = 0; i < model.getPurchases().size(); i++) {
            Purchase tmp = model.getPurchases().get(i);

            tableModel.addRow(new String[]{Integer.toString(tmp.getcantidad_Art()), tmp.getDesc(), Double.toString(tmp.getprecio_C() * total)});
        }

        this.purchasesPanel.setModel(tableModel);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPurchase;
    private javax.swing.JTextField amountArtText;
    private gui.article.ArticleSearchPanel articleSearchPanel1;
    private javax.swing.JButton deletePurchase;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceText;
    private common.CustomTable purchasesPanel;
    // End of variables declaration//GEN-END:variables

    public void updateMainComponent(Customer c) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void updateMainComponent(Article c) {
        model.setSelectedArticle(c);
    }

    public void updateMainComponent() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void reset() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
