/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPaymentsPanel.java
 *
 * Created on 17/07/2010, 04:16:47 PM
 */
package gui.paymnts;

import bussiness.Article;
import bussiness.Customer;
import common.MainPanelInterface;
import model.PaymentsModel;


/**
 *
 * @author RVAFOD
 */
public class MainPaymentsPanel extends javax.swing.JPanel implements MainPanelInterface {

    PaymentsModel model;


    /** Creates new form MainPaymentsPanel */
    public MainPaymentsPanel() {
        initComponents();
        model = new PaymentsModel();
        customerPaymentsPanel1.setCustomerModel(model);
       

        
    }

   



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerSearchPanel1 = new gui.customerinfo.CustomerSearchPanel();
        customerPaymentsPanel1 = new gui.paymnts.CustomerPaymentsPanel();

        setPreferredSize(new java.awt.Dimension(554, 541));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerPaymentsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(customerSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(customerSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerPaymentsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.paymnts.CustomerPaymentsPanel customerPaymentsPanel1;
    private gui.customerinfo.CustomerSearchPanel customerSearchPanel1;
    // End of variables declaration//GEN-END:variables

    public void updateMainComponent(Customer c) {

            model.setSelectedCustomer(c);
            customerPaymentsPanel1.updatePaymentsPanel();


    }

    public void updateMainComponent(Article c) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void updateMainComponent() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void reset() {

    //customerPaymentsPanel1.reset();
   

    }
}
