/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerButtonPanel.java
 *
 * Created on 17/07/2010, 03:01:44 PM
 */

package gui.customerinfo;

import common.MainPanelInterface;
import model.CustomerInfoModel;

/**
 *
 * @author Luc3
 */
public class CustomerButtonPanel extends javax.swing.JPanel {

    CustomerInfoModel model;
    /** Creates new form CustomerButtonPanel */
    public CustomerButtonPanel() {
        initComponents();


    }



     public void setModel( CustomerInfoModel model){
         
        this.model = model;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newClient = new javax.swing.JButton();
        editClient = new javax.swing.JButton();
        deleteClient = new javax.swing.JButton();

        newClient.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        newClient.setText("NUEVO CLIENTE");
        newClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClientActionPerformed(evt);
            }
        });

        editClient.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        editClient.setText("EDITAR CLIENTE");
        editClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClientActionPerformed(evt);
            }
        });

        deleteClient.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        deleteClient.setText("ELIMINAR CLIENTE");
        deleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newClient)
                    .addComponent(editClient)
                    .addComponent(deleteClient))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClientActionPerformed
    model.setAction("AGREGAR");

     ((MainPanelInterface)this.getParent()).updateMainComponent();
    }//GEN-LAST:event_newClientActionPerformed

    private void editClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClientActionPerformed
        model.setAction("EDITAR");

        ((MainPanelInterface)this.getParent()).updateMainComponent();
    }//GEN-LAST:event_editClientActionPerformed

    private void deleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClientActionPerformed
       model.setAction("ELIMINAR");
        ((MainPanelInterface)this.getParent()).updateMainComponent();

    }//GEN-LAST:event_deleteClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteClient;
    private javax.swing.JButton editClient;
    private javax.swing.JButton newClient;
    // End of variables declaration//GEN-END:variables

}
