/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainCustomerPanel.java
 *
 * Created on 17/07/2010, 04:42:53 PM
 */
package gui.customerinfo;

import bussiness.Article;
import bussiness.Customer;
import common.MainPanelInterface;
import model.CustomerInfoModel;
import java.awt.Component;

/**
 *
 * @author Luc3
 */
public class MainCustomerPanel extends javax.swing.JPanel implements MainPanelInterface {

    CustomerInfoModel model;

    /** Creates new form MainCustomerPanel */
    public MainCustomerPanel() {
        initComponents();
        model = new CustomerInfoModel();

        customerButtonPanel1.setModel(model);
        customerInfoPanel1.setModel(model);

        customerInfoPanel1.setVisible(false);
        customerSearchPanel1.setVisible(false);

    }

    private void setInvisiblePanels() {
        customerInfoPanel1.setVisible(false);
        customerSearchPanel1.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerSearchPanel1 = new gui.customerinfo.CustomerSearchPanel();
        jSeparator1 = new javax.swing.JSeparator();
        customerButtonPanel1 = new gui.customerinfo.CustomerButtonPanel();
        customerInfoPanel1 = new gui.customerinfo.CustomerInfoPanel();

        setPreferredSize(new java.awt.Dimension(554, 541));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(customerInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.customerinfo.CustomerButtonPanel customerButtonPanel1;
    private gui.customerinfo.CustomerInfoPanel customerInfoPanel1;
    private gui.customerinfo.CustomerSearchPanel customerSearchPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void updateMainComponent(Customer c) {


        customerInfoPanel1.setCustomerData(c, c.getid_C());
        customerInfoPanel1.setVisible(true);

       
    }

    public void setVisible(Component c, boolean visible) {

        c.setVisible(visible);

    }

    public void updateMainComponent(Article c) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void updateMainComponent() {


        setInvisiblePanels();
        if (model.getAction().equals("AGREGAR")) {
            customerInfoPanel1.setVisible(true);
        }

        if (model.getAction().equals("EDITAR")) {
            customerSearchPanel1.setVisible(true);
        }

        if (model.getAction().equals("ELIMINAR")) {
            customerSearchPanel1.setVisible(true);
        }


    }

    public void reset() {
        customerSearchPanel1.reset();
        customerInfoPanel1.reset();
    }
}
