/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 17/07/2010, 03:33:24 PM
 */
package gui.main;

import common.Constants;
import common.SQLBuilder;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author RVAFOD
 */
public class MainForm extends javax.swing.JFrame {


    /** Creates new form MainForm */
    public MainForm(String user, String profile) {
        super("Sistema de Cobranza");
        initComponents();
        mainPaymentsPanel1.setVisible(false);
        mainSalesPanel1.setVisible(false);
        mainPurchasesPanel1.setVisible(false);
        mainCustomerPanel1.setVisible(false);
        mainArticlePanel1.setVisible(false);
        jTabbedPane1.setVisible(false);
        mainReportsPanel1.setVisible(false);

        Constants.setDate();
        dateLabel.setText(Constants.getMenuDate());

        this.userValue.setText(user);
        this.profileValue.setText(profile);
        this.setLocationRelativeTo(null);

        this.setProfilePermits(profile);

    }

    public void cambiaColor(JButton boton, Color cc){
        boton.setForeground(cc);
        boton.setBackground(cc);
    }
    
    public final void visiblePanel(JPanel panel) {

        jLayeredPane1.moveToFront(panel);
        mainPaymentsPanel1.setVisible(false);
        mainSalesPanel1.setVisible(false);
        mainPurchasesPanel1.setVisible(false);
        mainCustomerPanel1.setVisible(false);
        mainArticlePanel1.setVisible(false);
        jTabbedPane1.setVisible(false);
        mainReportsPanel1.setVisible(false);
        panel.setVisible(true);
    }


    public final void setProfilePermits(String profile){

        if(profile.equals("Cobrador")){
            this.inventoryButton.setVisible(false);
            this.reportsButton.setVisible(false);
            this.configurationButton.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainPaymentsPanel1 = new gui.paymnts.MainPaymentsPanel();
        mainSalesPanel1 = new gui.sales.MainSalesPanel();
        mainCustomerPanel1 = new gui.customerinfo.MainCustomerPanel();
        mainPurchasesPanel1 = new gui.purchases.MainPurchasesPanel();
        mainReportsPanel1 = new gui.report.MainReportsPanel();
        mainArticlePanel1 = new gui.article.MainArticlePanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mainUsersPanel1 = new gui.users.MainUsersPanel();
        formatoTicketPanel1 = new common.FormatoTicketPanel();
        paymentsButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        purchasesButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        configurationButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        dateLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        userValue = new javax.swing.JLabel();
        profileValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        setForeground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleBackground"));
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(255, 0, 255));
        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLayeredPane1.setAutoscrolls(true);
        jLayeredPane1.setDoubleBuffered(true);
        mainPaymentsPanel1.setBounds(20, 20, 554, 480);
        jLayeredPane1.add(mainPaymentsPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainSalesPanel1.setBounds(10, 10, 560, 500);
        jLayeredPane1.add(mainSalesPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainCustomerPanel1.setBounds(20, 10, 554, 490);
        jLayeredPane1.add(mainCustomerPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainPurchasesPanel1.setBounds(20, 20, 560, 452);
        jLayeredPane1.add(mainPurchasesPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mainReportsPanel1.setMaximumSize(new java.awt.Dimension(390, 390));
        mainReportsPanel1.setBounds(30, 20, 530, 480);
        jLayeredPane1.add(mainReportsPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainArticlePanel1.setBounds(20, 20, 554, 480);
        jLayeredPane1.add(mainArticlePanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.addTab("Usuarios", mainUsersPanel1);
        jTabbedPane1.addTab("Ticket", formatoTicketPanel1);

        jTabbedPane1.setBounds(30, 10, 540, 480);
        jLayeredPane1.add(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        paymentsButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        paymentsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/money.png"))); // NOI18N
        paymentsButton.setText("ABONOS");
        paymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsButtonActionPerformed(evt);
            }
        });

        salesButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        salesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/addShopping.png"))); // NOI18N
        salesButton.setText("VENTAS");
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });

        reportsButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/report.png"))); // NOI18N
        reportsButton.setText("REPORTES");
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        purchasesButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        purchasesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/chop.png"))); // NOI18N
        purchasesButton.setText("COMPRAS");
        purchasesButton.setMaximumSize(new java.awt.Dimension(79, 23));
        purchasesButton.setMinimumSize(new java.awt.Dimension(79, 23));
        purchasesButton.setPreferredSize(new java.awt.Dimension(79, 23));
        purchasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasesButtonActionPerformed(evt);
            }
        });

        clientsButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        clientsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/clients.png"))); // NOI18N
        clientsButton.setText("CLIENTES");
        clientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsButtonActionPerformed(evt);
            }
        });

        inventoryButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        inventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/clothes.png"))); // NOI18N
        inventoryButton.setText("CATÁLOGO");
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        configurationButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        configurationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/configuration.png"))); // NOI18N
        configurationButton.setText("CONFIGURACIÓN");
        configurationButton.setMaximumSize(new java.awt.Dimension(79, 23));
        configurationButton.setMinimumSize(new java.awt.Dimension(79, 23));
        configurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/exit.png"))); // NOI18N
        exitButton.setText("SALIR");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        dateLabel.setText("Fecha:");

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        userLabel.setText("Usuario:");

        profileLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        profileLabel.setText("Perfil:");

        userValue.setText("NULL");

        profileValue.setText("NULL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userValue)
                .addGap(100, 100, 100)
                .addComponent(profileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(configurationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(purchasesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(reportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(inventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(clientsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(salesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(paymentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(profileLabel)
                    .addComponent(profileValue)
                    .addComponent(userValue)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paymentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchasesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsButtonActionPerformed

        visiblePanel(mainPaymentsPanel1);
        cambiaColor(paymentsButton, Color.BLUE);
        cambiaColor(salesButton, Color.BLACK);
        cambiaColor(reportsButton, Color.BLACK);
        cambiaColor(purchasesButton, Color.BLACK);
        cambiaColor(clientsButton, Color.BLACK);
        cambiaColor(inventoryButton, Color.BLACK);
        cambiaColor(configurationButton, Color.BLACK);

}//GEN-LAST:event_paymentsButtonActionPerformed

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed

        visiblePanel(mainSalesPanel1);
        cambiaColor(paymentsButton, Color.BLACK);
        cambiaColor(salesButton, Color.BLUE);
        cambiaColor(reportsButton, Color.BLACK);
        cambiaColor(purchasesButton, Color.BLACK);
        cambiaColor(clientsButton, Color.BLACK);
        cambiaColor(inventoryButton, Color.BLACK);
        cambiaColor(configurationButton, Color.BLACK);

        //jLayeredPane1.moveToFront(customerSearchPanel1);
}//GEN-LAST:event_salesButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        // TODO add your handling code here:
        visiblePanel(mainReportsPanel1);
        cambiaColor(paymentsButton, Color.BLACK);
        cambiaColor(salesButton, Color.BLACK);
        cambiaColor(reportsButton, Color.BLUE);
        cambiaColor(purchasesButton, Color.BLACK);
        cambiaColor(clientsButton, Color.BLACK);
        cambiaColor(inventoryButton, Color.BLACK);
        cambiaColor(configurationButton, Color.BLACK);
}//GEN-LAST:event_reportsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
//        visiblePanel(mainCustomerPanel1);
//        jLayeredPane1.moveToFront(mainCustomerPanel1);
        
        if (JOptionPane.showConfirmDialog(this, "¿Estas seguro de que desea salir de la aplicación?") == 0) {
            try {
                SQLBuilder.disconnect();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
            System.exit(0);

        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void purchasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasesButtonActionPerformed
        visiblePanel(mainPurchasesPanel1);
        cambiaColor(paymentsButton, Color.BLACK);
        cambiaColor(salesButton, Color.BLACK);
        cambiaColor(reportsButton, Color.BLACK);
        cambiaColor(purchasesButton, Color.BLUE);
        cambiaColor(clientsButton, Color.BLACK);
        cambiaColor(inventoryButton, Color.BLACK);
        cambiaColor(configurationButton, Color.BLACK);

    }//GEN-LAST:event_purchasesButtonActionPerformed

    private void clientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsButtonActionPerformed
        visiblePanel(mainCustomerPanel1);
        cambiaColor(paymentsButton, Color.BLACK);
        cambiaColor(salesButton, Color.BLACK);
        cambiaColor(reportsButton, Color.BLACK);
        cambiaColor(purchasesButton, Color.BLACK);
        cambiaColor(clientsButton, Color.BLUE);
        cambiaColor(inventoryButton, Color.BLACK);
        cambiaColor(configurationButton, Color.BLACK);
    }//GEN-LAST:event_clientsButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        visiblePanel(mainArticlePanel1);
        cambiaColor(paymentsButton, Color.BLACK);
        cambiaColor(salesButton, Color.BLACK);
        cambiaColor(reportsButton, Color.BLACK);
        cambiaColor(purchasesButton, Color.BLACK);
        cambiaColor(clientsButton, Color.BLACK);
        cambiaColor(inventoryButton, Color.BLUE);
        cambiaColor(configurationButton, Color.BLACK);

    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void configurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationButtonActionPerformed

        jLayeredPane1.moveToFront(jTabbedPane1);
        
                cambiaColor(paymentsButton, Color.BLACK);
        cambiaColor(salesButton, Color.BLACK);
        cambiaColor(reportsButton, Color.BLACK);
        cambiaColor(purchasesButton, Color.BLACK);
        cambiaColor(clientsButton, Color.BLACK);
        cambiaColor(inventoryButton, Color.BLACK);
        cambiaColor(configurationButton, Color.BLUE);
        
        mainPaymentsPanel1.setVisible(false);
        mainSalesPanel1.setVisible(false);
        mainPurchasesPanel1.setVisible(false);
        mainCustomerPanel1.setVisible(false);
        mainArticlePanel1.setVisible(false);
        mainReportsPanel1.setVisible(false);
        jTabbedPane1.setVisible(true);
        //visiblePanel(jTabbedPane1);
    

    }//GEN-LAST:event_configurationButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientsButton;
    private javax.swing.JButton configurationButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton exitButton;
    private common.FormatoTicketPanel formatoTicketPanel1;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private gui.article.MainArticlePanel mainArticlePanel1;
    private gui.customerinfo.MainCustomerPanel mainCustomerPanel1;
    private gui.paymnts.MainPaymentsPanel mainPaymentsPanel1;
    private gui.purchases.MainPurchasesPanel mainPurchasesPanel1;
    private gui.report.MainReportsPanel mainReportsPanel1;
    private gui.sales.MainSalesPanel mainSalesPanel1;
    private gui.users.MainUsersPanel mainUsersPanel1;
    private javax.swing.JButton paymentsButton;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel profileValue;
    private javax.swing.JButton purchasesButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JButton salesButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userValue;
    // End of variables declaration//GEN-END:variables
}
