/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArticleButtonPanel.java
 *
 * Created on 17/07/2010, 03:14:58 PM
 */

package gui.article;

import common.MainPanelInterface;
import model.ArticleInfoModel;

/**
 *
 * @author Luc3
 */
public class ArticleButtonPanel extends javax.swing.JPanel {

    ArticleInfoModel model;
    /** Creates new form ArticleButtonPanel */
    public ArticleButtonPanel() {
        initComponents();
    }

    public void setModel(ArticleInfoModel model){
        this.model = model;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regisArticle = new javax.swing.JButton();
        editArticle = new javax.swing.JButton();
        deleteArticle = new javax.swing.JButton();

        regisArticle.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        regisArticle.setText("REGISTRAR ARTÍCULO");
        regisArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisArticleActionPerformed(evt);
            }
        });

        editArticle.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        editArticle.setText("EDITAR ARTÍCULO");
        editArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editArticleActionPerformed(evt);
            }
        });

        deleteArticle.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        deleteArticle.setText("ELIMINAR ARTÍCULO");
        deleteArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteArticleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regisArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regisArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editArticle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(deleteArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regisArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisArticleActionPerformed

        model.setAction("AGREGAR");
        ((MainPanelInterface)this.getParent()).updateMainComponent();

    }//GEN-LAST:event_regisArticleActionPerformed

    private void editArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editArticleActionPerformed

        model.setAction("EDITAR");
        ((MainPanelInterface)this.getParent()).updateMainComponent();
    }//GEN-LAST:event_editArticleActionPerformed

    private void deleteArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteArticleActionPerformed

        model.setAction("ELIMINAR");
        ((MainPanelInterface)this.getParent()).updateMainComponent();
    }//GEN-LAST:event_deleteArticleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteArticle;
    private javax.swing.JButton editArticle;
    private javax.swing.JButton regisArticle;
    // End of variables declaration//GEN-END:variables

}
