/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainArticlePanel.java
 *
 * Created on 19/07/2010, 12:04:56 PM
 */
package gui.article;


import bussiness.Article;
import bussiness.Customer;
import common.MainPanelInterface;
import dao.ArticleDAO;
import model.ArticleInfoModel;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Luc3
 */
public class MainArticlePanel extends javax.swing.JPanel implements MainPanelInterface {

    static HashMap articleList;
    ArticleInfoModel model;

    /** Creates new form MainArticlePanel */
    public MainArticlePanel() {
        initComponents();
        model = new ArticleInfoModel();
        articleInfoPanel1.setModel(model);
        articleButtonPanel1.setModel(model);
        try {
            articleList = ArticleDAO.getArticleInfo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        setInvisiblePanels();
    }

    private void setInvisiblePanels(){
         articleSearchPanel1.setVisible(false);
        articleInfoPanel1.setVisible(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        articleSearchPanel1 = new gui.article.ArticleSearchPanel();
        articleInfoPanel1 = new gui.article.ArticleInfoPanel();
        jSeparator1 = new javax.swing.JSeparator();
        articleButtonPanel1 = new gui.article.ArticleButtonPanel();

        setPreferredSize(new java.awt.Dimension(554, 541));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(articleSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(articleInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(articleButtonPanel1, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(articleButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(articleSearchPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(articleInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.article.ArticleButtonPanel articleButtonPanel1;
    private gui.article.ArticleInfoPanel articleInfoPanel1;
    private gui.article.ArticleSearchPanel articleSearchPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public static HashMap getArticleList() {
        return articleList;
    }

    public static void setArticleList(HashMap list) {
        articleList = list;
    }

    public void updateMainComponent(Customer c) {
    }

    public void updateMainComponent(Article c) {
        articleInfoPanel1.setArticleInfo(c);
        articleInfoPanel1.setVisible(true);
    }

    public void updateMainComponent() {

        setInvisiblePanels();

        if (model.getAction().equals("AGREGAR")) {
            //articleInfoPanel1.setLocation(50, 50);
            articleInfoPanel1.setVisible(true);
        }

        if (model.getAction().equals("EDITAR")) {
            articleSearchPanel1.setVisible(true);
        }

        if (model.getAction().equals("ELIMINAR")) {
            articleSearchPanel1.setVisible(true);
        }

    }

    public void reset() {
        
    }
}
