/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormatoTicketPanel.java
 *
 * Created on 21/03/2011, 04:09:19 PM
 */
package common;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luc3
 */
public class FormatoTicketPanel extends javax.swing.JPanel {

    /** Creates new form FormatoTicketPanel */
    ArrayList<String> header = new ArrayList();
    ArrayList<String> footer = new ArrayList();
    LeerDatos leer = new LeerDatos();

    public FormatoTicketPanel() {
        initComponents();
        readInfo();
    }

    public void readInfo() {

        leer.leeDatos();

        StringBuilder bufferHeader = new StringBuilder();
        for (int x = 0; x < leer.getHeader().size(); x++) {
            bufferHeader.append(leer.getHeader().get(x).toString() + "\n");
        }
        headerTextArea.setText(bufferHeader.toString());

        StringBuilder bufferFooter = new StringBuilder();
        for (int x = 0; x < leer.getFooter().size(); x++) {
            bufferFooter.append(leer.getFooter().get(x).toString() + "\n");

        }

        footerTextArea.setText(bufferFooter.toString());

    }//readInfo

    public void writeInfo() throws IOException {

        header.clear();
        footer.clear();
        header.add(headerTextArea.getText());
        footer.add(footerTextArea.getText());

        LeerDatos escribir = new LeerDatos();
        escribir.escribirDatos(header, footer);
    }

    public void successfulMessage(String message) {

        JOptionPane.showMessageDialog(this.getParent(), message);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        headerTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        footerTextArea = new javax.swing.JTextArea();

        jButton1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel1.setText("Encabezado de Ticket:");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14));
        jLabel2.setText("Pie de Ticket");

        headerTextArea.setColumns(20);
        headerTextArea.setRows(5);
        jScrollPane1.setViewportView(headerTextArea);

        footerTextArea.setColumns(20);
        footerTextArea.setRows(5);
        jScrollPane2.setViewportView(footerTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (JOptionPane.showConfirmDialog(this.getParent(), "¿Está seguro que desea editar el Encabezado y Pie de página?") == 0) {
                writeInfo();
                String message = "El Encabezado y Pie de página fueron editados exitosamente";
                successfulMessage(message);
            }

        } catch (IOException ex) {
            Logger.getLogger(FormatoTicketPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea footerTextArea;
    private javax.swing.JTextArea headerTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
